export const skills = {
  linux: "Linux",
  docker: "Docker",
  k8s: "Kubernetes",
  script: "Script Bash",
  ansible: "Ansible",
  argocd: "ArgoCD",
  openshift: "Openshift",
  Mongo: "MongoDB",
  Postgresql: "PostgreSQL",
  html: "HTML",
  css: "CSS",
  python: "Python",
  node: "Node.js",
  jsts: "Javascript",
  aws: "AWS",
  git: "Git",
  flask: "Flask",
  django: "Django",
  figma: "Figma",
  powerbi: "Power Bi",
};
